---
# tasks file for postgresql
- name: install apt packages
  apt: >
    pkg={{ item }} update_cache=yes cache_valid_time=3600
    force=yes install_recommends=no state=present
  with_items:
    - libpq-dev
    - postgresql-{{ pg_version }}
    - postgresql-{{ pg_version }}-debversion
    - python-psycopg2

- name: copy configuration file
  template: >
    src=pg_hba.conf.j2
    dest=/etc/postgresql/{{ pg_version }}/main/pg_hba.conf
    owner=postgres
    group=postgres
    mode=0644
  notify: restart postgresql

- name: copy service file
  template: >
    src=pg_service.conf.j2
    dest=/etc/postgresql-common/pg_service.conf
    owner=postgres
    group=postgres
    mode=0644
  notify: restart postgresql

- name: remove database exists
  postgresql_db:
    name: "{{ database_name }}"
    state: "absent"
  sudo: True
  sudo_user: postgres

- name: remove user exists
  postgresql_user:
    name: "{{ database_user }}"
    state: "absent"
  sudo: True
  sudo_user: postgres

- name: create a user
  postgresql_user:
    name: "{{ database_user }}"
    password: "celinux2014"
    role_attr_flags: CREATEROLE,CREATEUSER
  sudo: True
  sudo_user: postgres

- name: create the database
  postgresql_db:
    name: "{{ database_name }}"
    owner: "{{ database_user }}"
    encoding: 'UTF-8'
    template: 'template0'
  sudo: True
  sudo_user: postgres



