# control-wanna-server.yml
# Usage: ansible-playbook ./control-wanna-server.yml -t reset-package-by-name,debug  --extra-vars "PACKAGE=tagainijisho_1.0.2-1"
---
- name: control wanna server
  hosts: wanna-build-server-test
  gather_facts: False
  vars:
    ARCH: amd64
    SUITE: jessie
    PLIST: default.list
    USAGE: |
      Usage:
      wannaplay reset-all
      ansible-playbook ./control-wanna-server.yml -t usage
      ansible-playbook ./control-wanna-server.yml -t reset-all
      ansible-playbook ./control-wanna-server.yml -t reset-by-name,debug  --extra-vars 'PACKAGES=tagainijisho_1.0.2-1'
      ansible-playbook ./control-wanna-server.yml -t query-by-name,debug  --extra-vars 'PACKAGES=tagainijisho_1.0.2-1,nut_2.7.2-4'
      ansible-playbook ./control-wanna-server.yml -t reset-by-list,debug  --extra-vars 'PLIST=X11.list'
  tasks:
    - name: print Usage
      debug: var=USAGE.split('\n')
      tags: usage

    - name: reset all packages of one suite to needs-build
      # there two kind of package name+version, can't use : as FS
      # - hamradio/xnec2c_1:3.0-1
      # - debian-installer/debian-installer-utils_1.110:
      # using pipe to avoid redirect I/O (MAY speed up)
      shell: |
        sudo -u wbadm /usr/bin/wanna-build -A {{ARCH}} --dist={{SUITE}} --list=bd-uninstallable |
        awk  ' {split($1,parts,"/");if(parts[2]!="") print parts[2]}' |
        sed  's/:$//g' |
        while read line; do
            sudo -u wbadm /usr/bin/wanna-build -A {{ARCH}} --dist={{SUITE}} --simulate-dose --override --needs-build $line -v
        done
      tags:
        - reset-all

    - name: reset packages state by name
      # handle a,b,  ,a,b
      shell: |
        echo {{PACKAGES}} | awk -vFS=',' -vOFS='\n' '{NF=NF;print $0}' | sed '/^\s*$/d' |
        while read line; do
            sudo -u wbadm /usr/bin/wanna-build -A {{ARCH}} --dist={{SUITE}} --simulate-dose --override --needs-build $line -v
        done
      register: out
      tags:
        - reset-by-name

    - name: query packages state by name
      shell: |
        echo {{PACKAGES}} | awk -vFS=',' -vOFS='\n' '{NF=NF;print $0}' | sed '/^\s*$/d' |
        while read line; do
            sudo -u wbadm /usr/bin/wanna-build -A {{ARCH}} --dist={{SUITE}} -i $line -v
        done
      register: out
      tags:
        - query-by-name

    - name: copy wanna-build src
      copy: src=./needs-build/{{PLIST}}  dest=/tmp/{{PLIST}}
      tags:
        - reset-by-list
    - name: reset packages state by list file
      shell: |
        while read line; do
            sudo -u wbadm /usr/bin/wanna-build -A {{ARCH}} --dist={{SUITE}} --simulate-dose --override --needs-build $line -v
        done < /tmp/{{PLIST}}
      register: out
      tags:
        - reset-by-list

    - debug: var=out.stdout_lines
      tags: debug

    - debug: var=out
      tags: debugall

#    - debug: msg="Usage ansible-playbook ./control-wanna-server.yml -t {{ item }}"
#      with_items:
#        - reset-all
#        - reset-package-by-name,debug  --extra-vars 'PACKAGE=tagainijisho_1.0.2-1'
#      tags:
#        - usage

