# control-buildd.yml
---
- name: control wanna server
  hosts: buildd2-httcloud,buildd3-httcloud
  gather_facts: False
  vars:
    USAGE: |
      Usage:
      wannaplay reset-all
      ansible-playbook ./control-buildd.yml -t usage
      ansible-playbook ./control-buildd.yml -t enable-buildd,debug
      ansible-playbook ./control-buildd.yml -t disable-buildd  -e 'PACKAGES=tagainijisho_1.0.2-1'
  tasks:
    - name: print Usage
      debug: var=USAGE.split('\n')
      tags: usage

    - name: enable-buildd
      shell: |
        rm -f ~buildd/NO-DAEMON-PLEASE
        kill -HUP `cat /var/run/crond.pid`
      register: out
      tags:
        - enable-buildd

    - debug: var=out.stdout_lines
      tags: debug

    - debug: var=out
      tags: debugall

