# control-wanna-server.yml
---
- name: control wanna server
  hosts: wanna-build-server-test
  gather_facts: False
  vars:
    ARCH: amd64
    SUITE: jessie
  tasks:
    - name: reset all packages of one suite to needs-build
      # there two kind of package name+version, can't use : as FS
      # one hamradio/xnec2c_1:3.0-1
      # another debian-installer/debian-installer-utils_1.110:
      # using pipe to avoid redirect I/O (MAY speed up)
      shell: |
        sudo -u wbadm /usr/bin/wanna-build -A {{ARCH}} --dist={{SUITE}} --list=bd-uninstallable |
        awk  ' {split($1,parts,"/");if(parts[2]!="") print parts[2]}' |
        sed  's/:$//g' |
        while read line; do
            sudo -u wbadm /usr/bin/wanna-build -A {{ARCH}} --dist={{SUITE}} --simulate-dose --override --needs-build $line -v
        done
      tags:
        - reset-all


