# install-wanna-build-server.yml
---
- name: install wanna-build server code
  hosts: wanna-build-server-test
  gather_facts: TRUE
  pre_tasks:
    - name: set local apt source
      apt_repository: repo='deb http://10.0.2.129/bxbos jessie main' state=present
    - apt_repository: repo='deb http://mirrors.163.com/debian jessie main' state=absent
 
    - name: install perl dependency
      apt: >
        pkg={{ item }} update_cache=yes cache_valid_time=3600
        force=yes install_recommends=no state=present
      with_items:
        - sudo
        - git
        - procmail
        - dctrl-tools
        - moreutils
        - libdpkg-perl
        - libdbi-perl
        - libyaml-tiny-perl
        - libhash-merge-perl
        - libstring-format-perl
        - libtimedate-perl
        - libyaml-libyaml-perl
        - liburi-perl
        - libdbd-pg-perl
        - dose-builddebcheck

    - name: get wanna-build code
      git: repo=http://10.0.2.131/cgit/wanna-build-server dest=/srv/wanna-build
      register: out

    - name: ln -s /srv/wanna-build/bin/wanna-build /usr/bin/wanna-build
      file: src=/srv/wanna-build/bin/wanna-build dest=/usr/bin/wanna-build  state=link

    - name: add user
      user: name=wbadm comment= shell=/bin/bash

    - name: create folder for wbadm
      file: path=/srv/wanna-build/tmp state=directory mode=0755 owner=wbadm
    - file: path=/srv/buildd.debian.org state=directory mode=0755 owner=wbadm
#
#  TODO the ssh cert should be a role
#
    - name: copy CA pub
      copy: >
        src=./roles/buildd/files/baixibao-linux-CA-key.pub
        dest=/etc/ssh/baixibao-linux-CA-key.pub
      tags: ssh-by-CA

    - name: add to TrustedUserCAKeys
      shell: |
        if ! grep -e "TrustedUserCAKeys" /etc/ssh/sshd_config ; then
            echo "TrustedUserCAKeys /etc/ssh/baixibao-linux-CA-key.pub" >> /etc/ssh/sshd_config
            kill -HUP `cat /run/sshd.pid`
        fi
      tags: ssh-by-CA

    - name: copy CA private
      copy: >
        src=./roles/buildd/files/baixibao-linux-CA-key
        dest=/tmp/baixibao-linux-CA-key
        mode=0600
      tags: ssh-by-CA

    - name: sign host key & add to HostCertificate
      shell: |
        ssh-keygen -h -s /tmp/baixibao-linux-CA-key \
                   -P baixibao2015 \
                   -I "%{{ansible_hostname}}%" \
                   -V +52w1d \
                   -n "{{ansible_hostname}},{{ansible_eth0.ipv4.address}},{{ansible_ssh_host}}" \
                   /etc/ssh/ssh_host_rsa_key.pub
        if ! grep -e HostCertificate /etc/ssh/sshd_config ; then
            echo "HostCertificate /etc/ssh/ssh_host_rsa_key-cert.pub" >> /etc/ssh/sshd_config
            kill -HUP `cat /run/sshd.pid`
        fi
      register: out
      tags: ssh-by-CA

    - debug: var=out
      tags: debug

  roles:
    - role: postgresql
      database_name: "wannadb"
      database_user: "wbadm"
      pg_service_name: "wanna-build"

- include: initialize-wanna-db.yml

#    - name: insert arch and dist via sql
#     command: psql -d wannadb -c "{{ item }}"
#      sudo_user: postgres
#      sudo: True
#      with_items:
#        - INSERT INTO distributions(distribution,build_dep_resolver,archive) VALUES ('jessie','',''), ('sid','','');

#    - name: Delete sql script
#      file: path="{{sometemplocation}}/my.sql" state=absent

#command: "ln -s /srv/wanna-build/bin/wanna-build /usr/bin/wanna-build"

#    - name: run install script
#      script: ./scripts/install-wanna-build.sh 
#      register: out    -

#    - name: copy wanna-build src
#      copy: src=./scripts/wanna-build-source-2015-05-21.tar.gz  dest=/tmp/wanna-build-source.tar.gz

#    - name: update ssh server
#      apt: name=openssh-server force=yes
#    - service: name=ssh state=restarted
