# install-wanna-build-server.yml
---
- name: install wanna-build server code
  hosts: wanna-build-server-test
#  gather_facts: no
  pre_tasks:
    - name: set local apt source
      apt_repository: repo='deb http://10.0.2.129/bxbos jessie main' state=present
    - apt_repository: repo='deb http://mirrors.163.com/debian jessie main' state=absent
 
    - name: install perl dependency
      apt: >
        pkg={{ item }} update_cache=yes cache_valid_time=3600
        force=yes install_recommends=no state=present
      register: out
      with_items:
        - sudo
        - git
        - procmail
        - dctrl-tools
        - moreutils
        - libdpkg-perl
        - libdbi-perl
        - libyaml-tiny-perl
        - libhash-merge-perl
        - libstring-format-perl
        - libtimedate-perl
        # for YAML::XS package
        - libyaml-libyaml-perl
        # for URI::Escape package
        - liburi-perl
        - libdbd-pg-perl
        # edos-debcheck REMOVED; should we install "edos-distcheck" ?
        - dose-builddebcheck

    - name: get wanna-build code
      git: repo=http://10.0.2.131/cgit/wanna-build-server dest=/srv/wanna-build
      register: out    

    - debug: var=out.stdout_lines

  roles:
    - role: postgresql
      database_name: "wannadb"
      database_user: "wbadm"
      pg_service_name: "wanna-build"

  post_tasks:
    - name: ln -s /srv/wanna-build/bin/wanna-build /usr/bin/wanna-build
      file: src=/srv/wanna-build/bin/wanna-build dest=/usr/bin/wanna-build  state=link

    - name: add user
      user: name=wbadm comment= shell=/bin/bash

    - name: create folder for wbadm
      file: path=/srv/wanna-build/tmp state=directory mode=0755 owner=wbadm

    - name: create tables via sql
      shell: "psql -d wannadb -f /srv/wanna-build/schema/main-tables.sql"
      sudo_user: postgres
      sudo: True

    - name: copy role.sql to remote
      copy:  src=./roles.sql dest="/srv/wanna-build/schema/refine-roles.sql"

    - name: create roles via sql
      shell: "psql -d wannadb -f /srv/wanna-build/schema/refine-roles.sql"
      sudo_user: postgres
      sudo: True

    - name: create arch-tables.sql
      shell: ARCHES="amd64 mips64el ppc64el ppc64"; rm -f /tmp/arches-tables.sql; for arch in $ARCHES; do sed -e "s/ARCH/$arch/g" < /srv/wanna-build/schema/arches-tables.in >> /tmp/arches-tables.sql ; done

#    - name: Delete sql script
#      file: path="{{sometemplocation}}/my.sql" state=absent

#command: "ln -s /srv/wanna-build/bin/wanna-build /usr/bin/wanna-build"

#    - name: run install script
#      script: ./scripts/install-wanna-build.sh 
#      register: out    -

#    - name: copy wanna-build src
#      copy: src=./scripts/wanna-build-source-2015-05-21.tar.gz  dest=/tmp/wanna-build-source.tar.gz

#    - name: update ssh server
#      apt: name=openssh-server force=yes
#    - service: name=ssh state=restarted
