# install-buildd.yml
---
- name: install buildd at compiling hosts
  hosts: "{{ HOST }}"
  gather_facts: True
  pre_tasks:
    - name: cleanup buildd hosts
      script: ./scripts/cleanup-buildd-host.sh
      register: out
      ignore_errors: True

    - debug: var=out

  roles:
    - role: buildd
 
