# install-wanna-build-server.yml
---
- name: install wanna-build server code
  hosts: wanna-build-server-test
  gather_facts: True
  pre_tasks:
    - name: clean up enviroment
      shell: |
       # remove line in sshd_config
       ls -al


 
    - name: create folder for wbadm
      file: path=/srv/wanna-build/tmp state=directory mode=0755 owner=wbadm

    - debug: var=out
      tags: debug

  roles:
    - role: wannabuild

- include: initialize-wanna-db.yml

#    - name: insert arch and dist via sql
#     command: psql -d wannadb -c "{{ item }}"
#      sudo_user: postgres
#      sudo: True
#      with_items:
#        - INSERT INTO distributions(distribution,build_dep_resolver,archive) VALUES ('jessie','',''), ('sid','','');

#    - name: Delete sql script
#      file: path="{{sometemplocation}}/my.sql" state=absent

#command: "ln -s /srv/wanna-build/bin/wanna-build /usr/bin/wanna-build"

#    - name: run install script
#      script: ./scripts/install-wanna-build.sh 
#      register: out    -

#    - name: copy wanna-build src
#      copy: src=./scripts/wanna-build-source-2015-05-21.tar.gz  dest=/tmp/wanna-build-source.tar.gz

#    - name: update ssh server
#      apt: name=openssh-server force=yes
#    - service: name=ssh state=restarted
