# install-buildd.yml
---
- name: install buildd at compiling hosts
  hosts: buildd1-httcloud,buildd2-httcloud
  gather_facts: False
  pre_tasks:
    - name: cleanup buildd hosts
      script: ./scripts/cleanup-buildd-host.sh
      register: out
      ignore_errors: True

#    - debug: var=out

  roles:
    - role: buildd
 
