# install-wanna-build-server.yml
---
- name: install wanna-build server code
  hosts: wanna-build-server-test
  gather_facts: TRUE
  pre_tasks:
    - name: set local apt source
      apt_repository: repo='deb http://10.0.2.129/bxbos jessie main' state=present
    - apt_repository: repo='deb http://mirrors.163.com/debian jessie main' state=absent
 
    - name: install perl dependency
      apt: >
        pkg={{ item }} update_cache=yes cache_valid_time=3600
        force=yes install_recommends=no state=present
      with_items:
        - sudo
        - git
        - procmail
        - dctrl-tools
        - moreutils
        - libdpkg-perl
        - libdbi-perl
        - libyaml-tiny-perl
        - libhash-merge-perl
        - libstring-format-perl
        - libtimedate-perl
        - libyaml-libyaml-perl
        - liburi-perl
        - libdbd-pg-perl
        - dose-builddebcheck

    - name: get wanna-build code
      git: repo=http://10.0.2.131/cgit/wanna-build-server dest=/srv/wanna-build
      register: out

    - name: ln -s /srv/wanna-build/bin/wanna-build /usr/bin/wanna-build
      file: src=/srv/wanna-build/bin/wanna-build dest=/usr/bin/wanna-build  state=link

    - name: add user
      user: name=wbadm comment= shell=/bin/bash

    - name: create folder for wbadm
      file: path=/srv/wanna-build/tmp state=directory mode=0755 owner=wbadm
    - file: path=/srv/buildd.debian.org state=directory mode=0755 owner=wbadm

    - debug: var=out
      tags: debug

  roles:
    - role: sshcert
      TYPE: "server"

    - role: postgresql
      database_name: "wannadb"
      database_user: "wbadm"
      pg_service_name: "wanna-build"

- include: initialize-wanna-db.yml

#    - name: insert arch and dist via sql
#     command: psql -d wannadb -c "{{ item }}"
#      sudo_user: postgres
#      sudo: True
#      with_items:
#        - INSERT INTO distributions(distribution,build_dep_resolver,archive) VALUES ('jessie','',''), ('sid','','');

#    - name: Delete sql script
#      file: path="{{sometemplocation}}/my.sql" state=absent

#command: "ln -s /srv/wanna-build/bin/wanna-build /usr/bin/wanna-build"

#    - name: run install script
#      script: ./scripts/install-wanna-build.sh 
#      register: out    -

#    - name: copy wanna-build src
#      copy: src=./scripts/wanna-build-source-2015-05-21.tar.gz  dest=/tmp/wanna-build-source.tar.gz

#    - name: update ssh server
#      apt: name=openssh-server force=yes
#    - service: name=ssh state=restarted
