# install-buildd.yml
# Usage:
# if install buildd for jessie-proposed-updates
# ansible-playbook ./install-buildd.yml -e HOST=buildd4*  -e SUITE=jessie-proposed-updates -e WANNA_HOST= -e DUPLOAD_INCOMING=
---
- name: install buildd at compiling hosts
  hosts: "{{ HOST }}"
  gather_facts: True
  pre_tasks:
    - name: cleanup buildd hosts
      script: ./scripts/cleanup-buildd-host.sh
      register: out
      ignore_errors: True

    - debug: var=out

  roles:
    - role: buildd
 
