---
# buildd copy keys

# What if there are illegal characters in localfile?
#- name: import keys
#  shell: |
#    echo "{{lookup('file','../files/buildd_key_pub.gpg.back')}}" |
#    gpg --import
#    echo "{{lookup('file','../files/buildd_key_sec.gpg')}}" |
#    gpg --import

#
# Copy user key to wanna-server for SSH
# echo StrictHostKeyChecking no >> ~/.ssh/config
# NO need now, using CA ssh auth
#

#
# change mode of private key to 0600
# or there will be a error by ssh
#
- name: chmod user private key to 0600
  file: path=~buildd/.ssh/id_rsa owner=buildd mode=0600

- name: copy key before import keys 
  copy: src=../files/buildd_key_pub.gpg dest=/tmp/ owner=buildd

- name: copy key before import keys 
  copy: src=../files/buildd_key_sec.gpg dest=/tmp/ owner=buildd

- name: import keys 
  shell: |
    gpg --import /tmp/buildd_key_pub.gpg 2>&1
    gpg --import /tmp/buildd_key_sec.gpg 2>&1
  become: True
  become_user: buildd
  ignore_errors: True
  register: out

- name: sbuild keys
  copy: src=../files/sbuild-key.pub dest=/var/lib/sbuild/apt-keys/ owner=sbuild

- name: sbuild sec keys
  copy: src=../files/sbuild-key.sec dest=/var/lib/sbuild/apt-keys/ owner=sbuild
