---
# buildd copy keys

# What if there are illegal characters in localfile?
#- name: import keys
#  shell: |
#    echo "{{lookup('file','../files/buildd_key_pub.gpg.back')}}" |
#    gpg --import
#    echo "{{lookup('file','../files/buildd_key_sec.gpg')}}" |
#    gpg --import

- name: copy key before import keys 
  copy: src=../files/buildd_key_pub.gpg dest=/tmp/ owner=buildd

- name: copy key before import keys 
  copy: src=../files/buildd_key_sec.gpg dest=/tmp/ owner=buildd

- name: import keys 
  shell: |
    gpg --import /tmp/buildd_key_pub.gpg 2>&1
    gpg --import /tmp/buildd_key_sec.gpg 2>&1
  become: True
  become_user: buildd
  ignore_errors: True
  register: out

- name: sbuild keys
  copy: src=../files/sbuild-key.pub dest=/var/lib/sbuild/apt-keys/ owner=sbuild

- name: sbuild sec keys
  copy: src=../files/sbuild-key.sec dest=/var/lib/sbuild/apt-keys/ owner=sbuild
