---
# tasks file for buildd
- name: install apt packages
  apt: >
    pkg={{ item }} update_cache=yes cache_valid_time=3600
    force=yes install_recommends=no state=present
  with_items:
    - sbuild
    - buildd
    - sudo
    - schroot

- name: disable buildd daemon during install
  file: path=/var/lib/buildd/NO-DAEMON-PLEASE state=touch mode=0644

- include: import-keys.yml
#
# TODO
# Set SBUILD_JOBS needed in buildd.conf
# Run `cat /proc/cpuinfo | grep "processor" | wc -l` in host
# Get the result, then set the value here
# How do this in ansible?
#
# 1. custom module return dict {ansible_facts:{SBUILD_JOBS:}}
# 2. register shell output then call set_fact
#
# Here choosing the FIRST one
#
- name: get facts by module
  get_cpuinfo:

#- name: get cpu number
#  shell: |
#    cat /proc/cpuinfo | grep "processor" | wc -l
#  register: cpu_number
#  tags: set_fact_cpu_number
#
#- set_fact: SBUILD_JOBS={{cpu_number.stdout}}
#  tags: set_fact_cpu_number

- name: buildd config file
  template: >
    src=template-buildd.conf.j2
    dest=/etc/buildd/buildd.conf
    mode=0644
#  notify: restart buildd

- name: dupload config file
  template: >
    src=dupload.conf.j2
    dest=/etc/dupload.conf
    mode=0644

- name: sbuild add buildd to sbuild group
  shell: sbuild-adduser buildd

- debug: var=out
  tags: debug

  
