CREATE ROLE amd64;
ALTER ROLE amd64 WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN;

CREATE ROLE buildd_amd64;
ALTER ROLE buildd_amd64 WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN;

CREATE ROLE mips64el;
ALTER ROLE mips64el WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN;

CREATE ROLE buildd_mips64el;
ALTER ROLE buildd_mips64el WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN;

CREATE ROLE ppc64el;
ALTER ROLE ppc64el WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN;

CREATE ROLE buildd_ppc64el;
ALTER ROLE buildd_ppc64el WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN;

CREATE ROLE ppc64;
ALTER ROLE ppc64 WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN;

CREATE ROLE buildd_ppc64;
ALTER ROLE buildd_ppc64 WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN;

CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN;

--
-- wb-buildd, wb_all, wb_security, wbadm
--
CREATE ROLE "wb-buildd";
ALTER ROLE "wb-buildd" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN;

CREATE ROLE wb_all;
ALTER ROLE wb_all WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN;

CREATE ROLE wb_security;
ALTER ROLE wb_security WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN;

CREATE ROLE wbadm;
ALTER ROLE wbadm WITH NOSUPERUSER INHERIT CREATEROLE CREATEDB LOGIN;

--
-- privilledges
--
GRANT amd64    TO wb_all GRANTED BY wbadm;
GRANT mips64el TO wb_all GRANTED BY wbadm;
GRANT ppc64el  TO wb_all GRANTED BY wbadm;
GRANT ppc64    TO wb_all GRANTED BY wbadm;

GRANT wb_all TO buildd_amd64 GRANTED BY wbadm;
GRANT wb_all TO buildd_mips64el GRANTED BY wbadm;
GRANT wb_all TO buildd_ppc64el GRANTED BY wbadm;
GRANT wb_all TO buildd_ppc64 GRANTED BY wbadm;

GRANT wb_all TO "wb-buildd" GRANTED BY wbadm;
GRANT wb_all TO wbadm GRANTED BY wbadm;

