# import-packages-to-wanna-db.yml 
---
- name: import packages to wanna databae
  script: ../files/trigger.local
  become_user: wbadm
  become: True
  register: out
  when: NEW is not defined

- name: import packages to wanna databae
  script: ../files/trigger-jpu.local
  become_user: wbadm
  become: True
  register: out
  when: NEW is defined

- debug: var=out

